# Site settings
title: Bruin Christensen
email: carleton.christensen@anu.edu.au
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bruinchristensen.net"

# Excluded files
exluded: Gemfile, Gemfile.lock, todo.md, .DS_Store, vendor, .bundle

# Build settings
markdown: kramdown

collections:
  descartes:
    output: true
    permalink: /courses/:collection/
    title: "PHIL1337 Descartes"
    abstract: "The materials I use for introductory courses on Ren√© Descartes"